import numpy as np
import matplotlib.pyplot as plt
print('')
print('')
print('--------------Start--------------')
print('')
print('Hello and Welcome to my app, which can build Graph, Vertical and Horizontal Bar Graphs and Pie Chart :)')
print('')
print('So lesss go:-')
print('')
nam=input('Enter a diagram (i.e. Graph, Vertical Bar Graph, Horizontal Bar Graph, Pie Chart) :- ').lower()
print('')
if nam == 'graph':
    print('Enter the dimensions of x and y axis respectively (Remember:- It supports only 3 parameters, for more contact tell the owner)  :)  ')
    print('')
    print('Enter the dimensions of the x axis:-')
    print('')
    n1=int(input('Enter the dimension 1 of the x axis:- '))
    print('')
    n2=int(input('Enter the dimension 2 of the x axis:- '))
    print('')
    n3=int(input('Enter the dimension 3 of the x axis:- '))
    x=np.array([n1,n2,n3])
    print('')
    print('Enter the dimensions of the y axis:-')
    print('')
    n4=int(input('Enter the dimension 1 of the y axis:- '))
    print('')
    n5=int(input('Enter the dimension 2 of the y axis:- '))
    print('')
    n6=int(input('Enter the dimension 3 of the y axis:- '))
    y=np.array([n4,n5,n6])
    print('')
    m1=input('Enter the marker:- ').lower()
    print('')
    m2=input('Enter the marker border color:- ').lower()
    print('')
    m3=input('Enter the marker color:- ').lower()
    print('')
    m4=input('Enter the line color:- ').lower()
    plt.plot(x,y,marker=m1,mec=m2,mfc=m3,ms=10,color=m4,linewidth=0.5)
    plt.title('Graph')
    plt.show()
elif nam == 'vertical bar graph':
    print('Enter the dimensions of x and y axis respectively (Remember:- It supports only 4 parameters, for more contact tell the owner)  :)  ')
    print('')
    print('Enter the dimensions of the x axis:-')
    print('')
    n1=int(input('Enter the dimension 1 of the x axis:- '))
    print('')
    n2=int(input('Enter the dimension 2 of the x axis:- '))
    print('')
    n3=int(input('Enter the dimension 3 of the x axis:- '))
    print('')
    n8=int(input('Enter the dimension 4 of the x axis:- '))
    print('')
    x=np.array([n1,n2,n3,n8])
    print('')
    print('Enter the dimensions of the y axis:-')
    print('')
    n4=int(input('Enter the dimension 1 of the y axis:- '))
    print('')
    n5=int(input('Enter the dimension 2 of the y axis:- '))
    print('')
    n6=int(input('Enter the dimension 3 of the y axis:- '))
    print('')
    n7=int(input('Enter the dimension 4 of the y axis:- '))
    print('')
    y=np.array([n4,n5,n6,n7])
    print('')
    m1=input('Enter the color for dimension 1:- ').lower()
    print('')
    m2=input('Enter the color for dimension 2:- ').lower()
    print('')
    m3=input('Enter the color for dimension 3:- ').lower()
    print('')
    m4=input('Enter the color for dimension 4:- ').lower()
    print('')
    plt.bar(x,y,color=[m1,m2,m3,m4],width=1.1)
    plt.title('Vertical Bar Graph')
    plt.show()
elif nam == 'horizontal bar graph':
    print('Enter the dimensions of x and y axis respectively (Remember:- It supports only 4 parameters, for more contact tell the owner)  :)  ')
    print('')
    print('Enter the dimensions of the x axis:-')
    print('')
    n1=int(input('Enter the dimension 1 of the x axis:- '))
    print('')
    n2=int(input('Enter the dimension 2 of the x axis:- '))
    print('')
    n3=int(input('Enter the dimension 3 of the x axis:- '))
    print('')
    n7=int(input('Enter the dimension 4 of the x axis:- '))
    print('')
    x=np.array([n1,n2,n3,n7])
    print('')
    print('Enter the dimensions of the y axis:-')
    print('')
    n4=int(input('Enter the dimension 1 of the y axis:- '))
    print('')
    n5=int(input('Enter the dimension 2 of the y axis:- '))
    print('')
    n6=int(input('Enter the dimension 3 of the y axis:- '))
    print('')
    n8=int(input('Enter the dimension 4 of the y axis:- '))
    print('')
    y=np.array([n4,n5,n6,n8])
    print('')
    m1=input('Enter the color for dimension 1:- ').lower()
    print('')
    m2=input('Enter the color for dimension 2:- ').lower()
    print('')
    m3=input('Enter the color for dimension 3:- ').lower()
    print('')
    m4=input('Enter the color for dimension 4:- ').lower()
    print('')
    plt.barh(x,y,color=[m1,m2,m3,m4],height=1.1)
    plt.title('Horizontal Bar Graph')
    plt.show()
elif nam == 'pie chart':
    print('Enter the dimensions of a axis (Remember:- It supports only 5 parameters, for more contact tell the owner)  :)  ')
    print('')
    print('Enter the dimensions of a axis:-')
    print('')
    n1=int(input('Enter the dimension 1 of the a axis:- '))
    print('')
    n2=int(input('Enter the dimension 2 of the a axis:- '))
    print('')
    n3=int(input('Enter the dimension 3 of the a axis:- '))
    print('')
    n4=int(input('Enter the dimension 4 of the a axis:- '))
    print('')
    n5=int(input('Enter the dimension 5 of the a axis:- '))
    print('')
    x=np.array([n1,n2,n3,n4,n5])
    print('')
    m1=input('Enter the label for dimension 1:- ').lower()
    print('')
    m2=input('Enter the label for dimension 2:- ').lower()
    print('')
    m3=input('Enter the label for dimension 3:- ').lower()
    print('')
    m4=input('Enter the label for dimension 4:- ').lower()
    print('')
    m5=input('Enter the label for dimension 5:- ').lower()
    print('')
    e1=float(input('Enter the value of explode in float for dimension 1:- '))
    print('')
    e2=float(input('Enter the value of explode in float for dimension 2:- '))
    print('')
    e3=float(input('Enter the value of explode in float for dimension 3:- '))
    print('')
    e4=float(input('Enter the value of explode in float for dimension 4:- '))
    print('')
    e5=float(input('Enter the value of explode in float for dimension 5:- '))
    print('')
    plt.pie(x,labels=[m1,m2,m3,m4,m5],explode=[e1,e2,e3,e4,e5],shadow=True,autopct='%1.1f%%')
    plt.title('Pie Chart')
    plt.legend(loc="lower left")
    plt.show()
print('')
print('----------------End-------------------')
print('')
print('')